/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Member;
import view.Petani;
import view.Profil;

/**
 *
 * @author djavu
 */
public class DataMember extends javax.swing.JFrame {

    /**
     * Creates new form DataMember
     */
    DefaultComboBoxModel comboJenisMember = new DefaultComboBoxModel();
    int baris = 0;
    static Object kolom[] = {"No.", "Nama", "Alamat", "Jenis Member"};
    DefaultTableModel tabel = new DefaultTableModel(kolom, baris);

    public DataMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data_member = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        edt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edt_alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        combo_jenis_member = new javax.swing.JComboBox<>();
        btn_reset = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        edt_cari = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_profil = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_member = new javax.swing.JMenuItem();
        menu_kategori = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_pembelian = new javax.swing.JMenuItem();
        menu_penjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Data Member");

        tabel_data_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_data_member);

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Jenis Member");

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        combo_jenis_member.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        menu_profil.setText("Profil");
        menu_profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_profilMouseReleased(evt);
            }
        });
        jMenu1.add(menu_profil);

        jMenuItem2.setText("Keluar");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseReleased(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        menu_member.setText("Data Member");
        menu_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_memberMouseReleased(evt);
            }
        });
        jMenu2.add(menu_member);

        menu_kategori.setText("Data Kategori");
        menu_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_kategoriMouseReleased(evt);
            }
        });
        jMenu2.add(menu_kategori);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        menu_pembelian.setText("Pembelian");
        menu_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_pembelianMouseReleased(evt);
            }
        });
        jMenu3.add(menu_pembelian);

        menu_penjualan.setText("Penjualan");
        menu_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_penjualanMouseReleased(evt);
            }
        });
        jMenu3.add(menu_penjualan);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_edit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edt_alamat)
                                    .addComponent(edt_nama)
                                    .addComponent(combo_jenis_member, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edt_cari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_jenis_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_update)
                    .addComponent(btn_reset)
                    .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Member m = new Member();
        //set to table member
        setDataTable(m);
        //set to list jenis member
        setDataCombo(m);
    }//GEN-LAST:event_formComponentShown

    private void menu_profilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_profilMouseReleased
        Profil profil = new Profil();
        this.setVisible(false);
        profil.setLocationRelativeTo(this);
        profil.setVisible(true);
    }//GEN-LAST:event_menu_profilMouseReleased

    private void jMenuItem2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseReleased
        Petani petani = new Petani();
        this.setVisible(false);
        petani.setLocationRelativeTo(this);
        petani.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MouseReleased

    private void menu_memberMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_memberMouseReleased
        DataMember dataMember = new DataMember();
        this.setVisible(false);
        dataMember.setLocationRelativeTo(this);
        dataMember.setVisible(true);
    }//GEN-LAST:event_menu_memberMouseReleased

    private void menu_kategoriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_kategoriMouseReleased
        DataHasilPanen dataHasilPanen = new DataHasilPanen();
        this.setVisible(false);
        dataHasilPanen.setLocationRelativeTo(this);
        dataHasilPanen.setVisible(true);
    }//GEN-LAST:event_menu_kategoriMouseReleased

    private void menu_pembelianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_pembelianMouseReleased
        Pembelian pembelian = new Pembelian();
        this.setVisible(false);
        pembelian.setLocationRelativeTo(this);
        pembelian.setVisible(true);
    }//GEN-LAST:event_menu_pembelianMouseReleased

    private void menu_penjualanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penjualanMouseReleased
        Penjualan penjualan = new Penjualan();
        this.setVisible(false);
        penjualan.setLocationRelativeTo(this);
        penjualan.setVisible(true);
    }//GEN-LAST:event_menu_penjualanMouseReleased

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String nama = edt_nama.getText();
        String alamat = edt_alamat.getText();
        String arrJenisMember[] = combo_jenis_member.getSelectedItem().toString().split("-");
        int idJenisMember = 0;
        idJenisMember = Integer.parseInt(arrJenisMember[0]);

        if (nama.isEmpty() || alamat.isEmpty() || idJenisMember == 0) {
            JOptionPane.showMessageDialog(this, "Field tidak boleh kosong");
        } else {
            Member m = new Member();
            int isCek = m.cekUser(nama, alamat);
            if (isCek == 0) {
                m.insertDataMember(nama, alamat, idJenisMember);
                setDataTable(m);
                edt_nama.setText("");
                edt_alamat.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Data sudah ada");
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        edt_nama.setText("");
        edt_alamat.setText("");
        Member m = new Member();
        setDataCombo(m);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int row = tabel_data_member.getSelectedRow();
        String nama = tabel_data_member.getValueAt(row, 1).toString();
        String alamat = tabel_data_member.getValueAt(row, 2).toString();

        if (nama.isEmpty() || alamat.isEmpty()) {

        } else {
            Member m = new Member();
            int id = m.getIdUser(nama, alamat);
            if (id != 0) {
                String data[][] = m.getProfilById(id);
                edt_nama.setText(data[0][0]);
                edt_alamat.setText(data[0][1]);
                //set to combo jenis
                int idJenis = m.getIDJenisMember(data[0][2]);
//                System.out.println(""+idJenis);
                String[] jMember = m.getListJenisMemberById(idJenis);
                if (jMember != null) {
                    comboJenisMember.removeAllElements();
                    comboJenisMember.addElement(jMember[0]);
                    combo_jenis_member.setModel(comboJenisMember);
                }
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String nama = edt_nama.getText();
        String alamat = edt_alamat.getText();
        String arrJenisMember[] = combo_jenis_member.getSelectedItem().toString().split("-");
        int idJenisMember = 0;
        idJenisMember = Integer.parseInt(arrJenisMember[0]);

        if (nama.isEmpty() || alamat.isEmpty() || idJenisMember == 0) {
            JOptionPane.showMessageDialog(this, "Field tidak boleh kosong");
        } else {
            Member m = new Member();
            int isCek = m.cekUser(nama, alamat);
            if (isCek != 0) {
                m.updateDataMember(nama, alamat, idJenisMember);
                //set data to table
                setDataTable(m);
                edt_nama.setText("");
                edt_alamat.setText("");
                setDataCombo(m);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        Member m = new Member();
        int row = tabel_data_member.getSelectedRow();
        String nama = tabel_data_member.getValueAt(row, 1).toString();
        String alamat = tabel_data_member.getValueAt(row, 2).toString();
        int id = m.getIdUser(nama, alamat);

        if (id != 0) {
            m.deleteData(id);
            setDataTable(m);
        }
        tabel.fireTableDataChanged();
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMember().setVisible(true);
            }
        });
    }

    //set to combo member
    private void setDataCombo(Member m) {
        comboJenisMember.removeAllElements();
        String listMember[] = m.getListJenisMember();
        if (listMember.length > 0) {
            for (int i = 0; i < listMember.length; i++) {
                comboJenisMember.addElement(listMember[i]);
            }
            combo_jenis_member.setModel(comboJenisMember);
        }
    }

    //set data table member
    private void setDataTable(Member m) {
        tabel.getDataVector().removeAllElements();
        String data[][] = m.getDataMember();
        if (data.length > 0) {
            for (int i = 0; i < data.length; i++) {
                int no = i + 1;
                tabel.addRow(new Object[]{no, data[i][0], data[i][1], data[i][2]});
            }
            tabel_data_member.setModel(tabel);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_jenis_member;
    private javax.swing.JTextField edt_alamat;
    private javax.swing.JTextField edt_cari;
    private javax.swing.JTextField edt_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_kategori;
    private javax.swing.JMenuItem menu_member;
    private javax.swing.JMenuItem menu_pembelian;
    private javax.swing.JMenuItem menu_penjualan;
    private javax.swing.JMenuItem menu_profil;
    private javax.swing.JTable tabel_data_member;
    // End of variables declaration//GEN-END:variables
}
