/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.User;
import view.admin.DataHasilPanen;
import view.admin.DataMember;
import view.admin.Pembelian;
import view.admin.Penjualan;
import view.manager.DataUser;
import view.manager.LaporanPembelian;
import view.manager.LaporanPenjualan;

/**
 *
 * @author djavu
 */
public class Profil extends javax.swing.JFrame {

    /**
     * Creates new form Profil
     */
    //variable global
    private String username = null;
    private String password = null;
    private String status = null;

    public Profil() {
        initComponents();
        User user = new User();
        String[][] data = user.getProfilById(User.getIDUser());
        if (data.length > 0) {
            edt_nama.setText(data[0][0]);
            edt_email.setText(data[0][1]);
            username = data[0][2];
            password = data[0][3];
            //set status
            status = data[0][4];
            tv_status_login.setText(status);
            //set enable false edt
            edt_username.setVisible(false);
            edt_password.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edt_nama = new javax.swing.JTextField();
        edt_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edt_username = new javax.swing.JTextField();
        tv_username = new javax.swing.JLabel();
        edt_password = new javax.swing.JTextField();
        tv_passwd = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tv_status_login = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_profil = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_admin_data = new javax.swing.JMenu();
        menu_member = new javax.swing.JMenuItem();
        menu_kategori = new javax.swing.JMenuItem();
        menu_admin_transaksi = new javax.swing.JMenu();
        menu_pembelian = new javax.swing.JMenuItem();
        menu_penjualan = new javax.swing.JMenuItem();
        menu_manager_laporan = new javax.swing.JMenu();
        menu_laporan_pembelian = new javax.swing.JMenuItem();
        menu_laporan_penjualan = new javax.swing.JMenuItem();
        menu_manager_data = new javax.swing.JMenu();
        menu_data_user = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Profil");

        jLabel2.setText("Nama");

        jLabel3.setText("Email");

        tv_username.setText("Username");

        tv_passwd.setText("Password");

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jLabel5.setText("Login sebagai");

        tv_status_login.setText("jLabel6");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        menu_profil.setText("Profil");
        menu_profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_profilMouseReleased(evt);
            }
        });
        jMenu1.add(menu_profil);

        jMenuItem2.setText("Keluar");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseReleased(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        menu_admin_data.setText("Master Data");

        menu_member.setText("Data Member");
        menu_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_memberMouseReleased(evt);
            }
        });
        menu_admin_data.add(menu_member);

        menu_kategori.setText("Data Kategori");
        menu_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_kategoriMouseReleased(evt);
            }
        });
        menu_admin_data.add(menu_kategori);

        jMenuBar1.add(menu_admin_data);

        menu_admin_transaksi.setText("Transaksi");

        menu_pembelian.setText("Pembelian");
        menu_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_pembelianMouseReleased(evt);
            }
        });
        menu_admin_transaksi.add(menu_pembelian);

        menu_penjualan.setText("Penjualan");
        menu_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_penjualanMouseReleased(evt);
            }
        });
        menu_admin_transaksi.add(menu_penjualan);

        jMenuBar1.add(menu_admin_transaksi);

        menu_manager_laporan.setText("Laporan");

        menu_laporan_pembelian.setText("Laporan Pembelian");
        menu_laporan_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_laporan_pembelianMouseReleased(evt);
            }
        });
        menu_manager_laporan.add(menu_laporan_pembelian);

        menu_laporan_penjualan.setText("Laporan Penjualan");
        menu_laporan_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_laporan_penjualanMouseReleased(evt);
            }
        });
        menu_manager_laporan.add(menu_laporan_penjualan);

        jMenuBar1.add(menu_manager_laporan);

        menu_manager_data.setText("Data");

        menu_data_user.setText("Data User");
        menu_data_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_data_userMouseReleased(evt);
            }
        });
        menu_manager_data.add(menu_data_user);

        jMenuBar1.add(menu_manager_data);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tv_username)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edt_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(tv_passwd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_simpan))
                                        .addComponent(edt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tv_status_login, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tv_status_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_username)
                    .addComponent(edt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_passwd)
                    .addComponent(edt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_simpan))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //set visible label password and edt password
        edt_username.setVisible(false);
        edt_password.setVisible(false);
        tv_username.setVisible(false);
        tv_passwd.setVisible(false);
        //set access user
        if (status.equalsIgnoreCase("admin")) {
            menu_manager_data.setVisible(false);
            menu_manager_laporan.setVisible(false);
        } else {
            menu_admin_transaksi.setVisible(false);
            menu_admin_data.setVisible(false);
        }
    }//GEN-LAST:event_formComponentShown

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        edt_username.setVisible(true);
        edt_password.setVisible(true);
        tv_username.setVisible(true);
        tv_passwd.setVisible(true);
        //set data
        edt_username.setText(username);
        edt_password.setText(password);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        User user = new User();

        String nama = edt_nama.getText();
        String email = edt_email.getText();
        String username = edt_username.getText();
        String passsword = edt_password.getText();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama harus diisi",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email harus diisi",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username harus diisi",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        } else if (passsword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Passowrd harus diisi",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        } else {
            user.updateProfil(username, passsword, email, nama, User.getIDUser());
            JOptionPane.showMessageDialog(this, "Update berhasil",
                    "Pesan Informasi", JOptionPane.INFORMATION_MESSAGE);
            //set visible label password and edt password
            edt_username.setVisible(false);
            edt_password.setVisible(false);
            tv_username.setVisible(false);
            tv_passwd.setVisible(false);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void menu_profilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_profilMouseReleased
        Profil profil = new Profil();
        this.setVisible(false);
        profil.setLocationRelativeTo(this);
        profil.setVisible(true);
    }//GEN-LAST:event_menu_profilMouseReleased

    private void jMenuItem2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseReleased
        Petani petani = new Petani();
        this.setVisible(false);
        petani.setLocationRelativeTo(this);
        petani.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MouseReleased

    private void menu_memberMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_memberMouseReleased
        DataMember dataMember = new DataMember();
        this.setVisible(false);
        dataMember.setLocationRelativeTo(this);
        dataMember.setVisible(true);
    }//GEN-LAST:event_menu_memberMouseReleased

    private void menu_kategoriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_kategoriMouseReleased
        DataHasilPanen dataHasilPanen = new DataHasilPanen();
        this.setVisible(false);
        dataHasilPanen.setLocationRelativeTo(this);
        dataHasilPanen.setVisible(true);
    }//GEN-LAST:event_menu_kategoriMouseReleased

    private void menu_pembelianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_pembelianMouseReleased
        Pembelian pembelian = new Pembelian();
        this.setVisible(false);
        pembelian.setLocationRelativeTo(this);
        pembelian.setVisible(true);
    }//GEN-LAST:event_menu_pembelianMouseReleased

    private void menu_penjualanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penjualanMouseReleased
        Penjualan penjualan = new Penjualan();
        this.setVisible(false);
        penjualan.setLocationRelativeTo(this);
        penjualan.setVisible(true);
    }//GEN-LAST:event_menu_penjualanMouseReleased

    private void menu_laporan_pembelianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_laporan_pembelianMouseReleased
        //for manager
        LaporanPembelian p = new LaporanPembelian();
        this.setVisible(true);
        p.setLocationRelativeTo(this);
        p.setVisible(true);
    }//GEN-LAST:event_menu_laporan_pembelianMouseReleased

    private void menu_laporan_penjualanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_laporan_penjualanMouseReleased
        //for manager
        LaporanPenjualan lp = new LaporanPenjualan();
        this.setVisible(true);
        lp.setLocationRelativeTo(this);
        lp.setVisible(true);
    }//GEN-LAST:event_menu_laporan_penjualanMouseReleased

    private void menu_data_userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_data_userMouseReleased
        DataUser user = new DataUser();
        this.setVisible(true);
        user.setLocationRelativeTo(this);
        user.setVisible(true);
    }//GEN-LAST:event_menu_data_userMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JTextField edt_email;
    private javax.swing.JTextField edt_nama;
    private javax.swing.JTextField edt_password;
    private javax.swing.JTextField edt_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menu_admin_data;
    private javax.swing.JMenu menu_admin_transaksi;
    private javax.swing.JMenuItem menu_data_user;
    private javax.swing.JMenuItem menu_kategori;
    private javax.swing.JMenuItem menu_laporan_pembelian;
    private javax.swing.JMenuItem menu_laporan_penjualan;
    private javax.swing.JMenu menu_manager_data;
    private javax.swing.JMenu menu_manager_laporan;
    private javax.swing.JMenuItem menu_member;
    private javax.swing.JMenuItem menu_pembelian;
    private javax.swing.JMenuItem menu_penjualan;
    private javax.swing.JMenuItem menu_profil;
    private javax.swing.JLabel tv_passwd;
    private javax.swing.JLabel tv_status_login;
    private javax.swing.JLabel tv_username;
    // End of variables declaration//GEN-END:variables
}
